name: clima_interior
description: "Clima no Interior"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
  
  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900